### ISSUE TITLE
discrepancy in pigrep: it prints "(stdin)" if file is "-" and prints nothing if no file provided

### ISSUE THREAD

**Issue by starius** [yandex/pire#15]
```
$ echo test | pigrep '^test$'
test
$ echo test | pigrep '^test$' -
(stdin)test

```

**Comment by dprokoptsev** [comment]
Look at grep(1), it has exactly the same behaviour (a little difference is that it prints a filename only if two or more files are given).

**Comment by starius** [comment]
> it prints a filename only if two or more files are given

This behaviour makes sense. Printing filename for single file is redundant.

Grep prints ':' after `(standard input)`. pigrep doesn't.

**Comment by dprokoptsev** [comment]
Fixed already.
