### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [yandex/pire#80]
Hi!

Thank you for the such cool library! I'm interested in packaging the library into some dependecy managers. It will be much easier if you make a release on GitHub, so in a package recipe I will rely on some "stable" version instead of specific commit. E.g. it much easier to create a package for Conan with release.

I found that from the last release (in 2013 - 7 years ago) there are a lot of changes. Will be fine if they will be released.

Thank you!

**Comment by sergey-v-galtsev** [comment]
Hi!

We have made a new release: [release-0.0.6](https://github.com/yandex/pire/releases/tag/release-0.0.6).
